spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 1234
    url: jdbc:mysql://vm:3306/demo_dev

  rabbitmq:
    host: vm
    port: 5672
    username: lihong
    password: 12345678

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true
---
spring:
  profiles: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 1234
    url: jdbc:mysql://vm:3306/demo_test

  rabbitmq:
    host: vm
    port: 5672
    username: lihong
    password: 12345678

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true
