server:
  port: 8888

eureka:
  instance:
    hostname: configserver
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/echoerror/spring-cloud-demo/
          search-paths: config-repo
      enabled: true
  rabbitmq:
        host: vm
        port: 5672
        username: lihong
        password: 12345678
